### ISSUE TITLE
Black Screen When Connecting 

### ISSUE THREAD

**Issue by DewayneDebbs** [alvr-org/alvr-visionos#105]
Client: ALVR 20.7.1 Testflight
Server: nightly 20.0.0-dev15-nightly-2023.06.01
PC: Windows 11 Home, i5-13600k, RTX 4080, 32GB

After finally getting ALVR to connect from Vision Pro to my Windows PC, which took tons of research and asking on Discord to find compatible software versions, I see only a black screen with my hands overlaid. Does anyone know why this might happen? When mentioning this in the discord others chimed in saying they had the same and we can't seem to find any way to make this function. Any help would be greatly appreciated.

It's probably notable that I believe most new users are following this Reddit post:

https://www.reddit.com/r/VisionPro/comments/1bmn6gd/getting_started_with_alvr_on_vision_pro/

**Comment by shinyquagsire23** [comment]
Most likely reason would be the encoder is failing on the PC-side.

- If you open up the SteamVR VR view on a monitor, does it track your head? You can open the control center to make the view semitransparent. If it doesn't track, then it's something else.
- Try turning down the encoder to Low, and setting it to H264, and then slowly bring it higher res.
- It might be worth resetting to stock settings (delete session.json) to find out what made it fail

**Comment by liushihai** [comment]
Use the latest version of windows alvr , or lower the alvr app of Vision Pro to a previous version. This is my solution, it can work

**Comment by AidenShanks** [comment]
I am having the same issue on my AVP. Using the “Display VR View” on steam VR works and you can see the headset tracking and click on things with a controller (I’m using switch controllers paired to the headset), but all you see in the headset is a black screen and hand overlays. I tried fully reinstalling with stock settings, various quality settings, and I was already on h264, but nothing worked.

**Comment by AidenShanks** [comment]
Using TestFlight version 20.7.1(5) solved the issue for me. I don’t know why in (6) it wasn’t working for me because it’s seemed like it was just a menu update but I don’t know for sure.

**Comment by shinyquagsire23** [comment]
ok actually yep there was a bug, it should be fixed now in 20.7.1(7)

**Comment by DewayneDebbs** [comment]
Confirmed resolved and functioning now with server build nightly 20.7.1. I did observe that there is a protocol error when attempting to use VB Cable with the wrong settings that appears similar to using mismatched server versions.
