### ISSUE TITLE
Testflight only shows V20.7.1 on Vision Pro, V20.8.1 not available anymore

### ISSUE THREAD

**Issue by cyrilpreiss** [alvr-org/alvr-visionos#110]
I had V20.8.1 installed on my Vision Pro and this morning the app reverted back to V20.7.1 and i can't find V20.8.1 anymore.
The connection with the computer doesn't work anymore...

**Comment by shinyquagsire23** [comment]
I never updated to v20.8.1, waiting for the app store review (or at least I was, reconsidering that tbh)

**Comment by cyrilpreiss** [comment]
it was using Testfilight invite:
https://testflight.apple.com/join/YoK2nuX6

will v21 be available for the vision pro anytime soon ?

**Comment by shinyquagsire23** [comment]
there's a v21 nightly teatflight at https://testflight.apple.com/join/GvAdO0DF

**Comment by cyrilpreiss** [comment]
Great thanks!

Envoyé à partir de Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Max Thomas ***@***.***>
Envoyé : Monday, June 10, 2024 8:43:30 PM
À : alvr-org/alvr-visionos ***@***.***>
Cc : cyrilpreiss ***@***.***>; Author ***@***.***>
Objet : Re: [alvr-org/alvr-visionos] Testflight only shows V20.7.1 on Vision Pro, V20.8.1 not available anymore (Issue #110)


there's a v21 nightly teatflight at https://testflight.apple.com/join/GvAdO0DF

**Comment by cyrilpreiss** [comment]
i tried this link, it installs v1, i guess it's v21
i have installed ALVR v21.0.0-dev00+nightly.2024.05.05 as asked in testflight dialog but i'm getting an incompatible protocol error.

**Comment by shinyquagsire23** [comment]
then you either need the nightly streamer, or to use the other testflight

**Comment by cyrilpreiss** [comment]
i tired with nightly 2024.05.05 and nightly 2024 06 10
i'm getting : "Trusted client is incompatible! Expected protocol ID: 15569632614514957802, found 7466344377858005457"

**Comment by shinyquagsire23** [comment]
yeah it needs the nightly specified in the testflight description
