### ISSUE TITLE
Can’t run app against any nightly ALVR streamer past May or released version 

### ISSUE THREAD

**Issue by ant2002k** [alvr-org/alvr-visionos#113]
Hello guys, I’m not sure what’s happening here, but the latest nightly sometime in the last month changed to a
”Dev01” Version of protocol which is not compatible with the current main build here. 

The last stable release of of ALVR streamer, which claims compatibility with this visionOS. Client also does not work, giving off incompatible protocol errors.

I’m only able to run the latest vision West release against the last nightly release that was “dev00”. 

Any ideas how to fix this?  Everything works fine and in fact in incredibly well under vision, OS 2.0 much smoother than before… And I’m able to use games with hand tracking that I could never do before. So well done. But I’m wondering what I’m missing here regarding synchronizing the protocols With the latest releases?

Thanks!

**Comment by shinyquagsire23** [comment]
Currently the only option is to downgrade the streamer, I should probably actually get around to upgrading the streaming framework to the newer protocols. But the Testflight has a working build linked in the info text.

**Comment by shinyquagsire23** [comment]
Specifically, https://github.com/alvr-org/ALVR-nightly/releases/tag/v21.0.0-dev00%2Bnightly.2024.05.05 is the one that should be set (and probably any other dev00 builds)

**Comment by ant2002k** [comment]
Thanks :). That build is what I have been using.  Things are working extremely well with the latest build and VisionOS 2.0 (and shutting off Airdrop and handoff 🙃) … you’ve done such a good job sign this.
