### ISSUE TITLE
Feature Request: Toggle Joystic Gestures Only

### ISSUE THREAD

**Issue by minusreality** [alvr-org/alvr-visionos#115]
When using a controller with joysticks, the specific gestures related to joysticks will conflict with the physical controller joysticks causing erratic behavior. I'd like to be able to disable only the joystick gestures so that I can use my controller joysticks for locomotion and my hands for everything else. Would this be possible?

**Comment by shinyquagsire23** [comment]
This would have to be an ALVR streamer feature request, so probably best to file it at https://github.com/alvr-org/ALVR/issues

**Comment by minusreality** [comment]
Issue was moved to ALVR Server's Github repo at https://github.com/alvr-org/ALVR/issues/2196
