### ISSUE TITLE
Consistent lag spikes/stuttering that wont go away

### ISSUE THREAD

**Issue by KevinTheNoob69** [alvr-org/alvr-visionos#117]
basically ive got my vision pro and ive got my pc. I'm running alvr on a very decent hardware(4070ti super + 64g ram) and a decent 5Ghz wifi 7 network router. The router is in sight and the average download speed is over 500mbps. Yet whenever I boot alvr and connect my devices there will be a consistent non-stop lag spike/stuttering that happens in a constant close interval (like about 0.3 seconds between each spike). I've tried lowering the framerates, the bitrates, the encoder preset, the adaptive bitrate settings and everything yet the spikes just stays. I'm running the testflight alvr 20.8.2(6) version with the v20.8.1 nightly release for the pc end and the vision OS version is 2.0 (im not very sure whether it is 2.0 or the beta 2.2 or whatever since I had beta tests on).
![asd11123](https://github.com/alvr-org/alvr-visionos/assets/174326066/139ceadf-bede-4861-96d8-4945c0f418d6)
![qaweasd](https://github.com/alvr-org/alvr-visionos/assets/174326066/cd75bbd5-c8f5-4281-88f4-cdc7c141afb4)

**Comment by shinyquagsire23** [comment]
that's AWDL probably, did you make sure to disable Handoff and Airdrop and/or change your router channel to channel 149?

**Comment by KevinTheNoob69** [comment]
yup it works now after i disabled handoff and airdrop. Thanks!
