### ISSUE TITLE
App launches, shows test RGB cube, loops connecting-disconnecting.

### ISSUE THREAD

**Issue by SwaMusic** [alvr-org/alvr-visionos#18]
SteamVR Overlay shows up with menu and applications but keeps disconnecting-connecting-disconnecting loop.

**Comment by shinyquagsire23** [comment]
hmmm, I've had it happen sometimes, but usually it resolves itself by closing out ALVR+SteamVR, closing the app on the headset, and then starting ALVR+SteamVR and then the app again. But tbh I'll keep this marked as a bug bc it's persistent enough to warrant a bit of extra care

**Comment by shinyquagsire23** [comment]
oh also, because I just ran into this bug: hold the top button and the crown for a few seconds, and make sure there aren't any ghost instances of ALVRClient, sometimes the Xcode debugger doesn't clean up properly. And also make sure to use Medium (4288) or lower resolution, because I don't think the Vision Pro decoder can decode higher than that.

**Comment by SwaMusic** [comment]
> oh also, because I just ran into this bug: hold the top button and the crown for a few seconds, and make sure there aren't any ghost instances of ALVRClient, sometimes the Xcode debugger doesn't clean up properly. And also make sure to use Medium (4288) or lower resolution, because I don't think the Vision Pro decoder can decode higher than that.

I am new to this. Where do we set those settings?

**Comment by SwaMusic** [comment]
> oh also, because I just ran into this bug: hold the top button and the crown for a few seconds, and make sure there aren't any ghost instances of ALVRClient, sometimes the Xcode debugger doesn't clean up properly. And also make sure to use Medium (4288) or lower resolution, because I don't think the Vision Pro decoder can decode higher than that.

Oh wait! I see now. It's on the desktop client, **not** XCode. 😅

**Comment by SwaMusic** [comment]
> oh also, because I just ran into this bug: hold the top button and the crown for a few seconds, and make sure there aren't any ghost instances of ALVRClient, sometimes the Xcode debugger doesn't clean up properly. And also make sure to use Medium (4288) or lower resolution, because I don't think the Vision Pro decoder can decode higher than that.

Got it working!!! Thank you so much for all of your help!! Looking forward to future iterations!! :)
