### ISSUE TITLE
Better timewarp/spacewarp

### ISSUE THREAD

**Issue by shinyquagsire23** [alvr-org/alvr-visionos#23]
The current trick of setting the Drawable anchor to the same timestamp as a received frame works well at full framerate, but has some adverse side-effects with our constant depth buffer. When moving your head forward an old frame, the view zooms in too much (the severity seems to depend on the depth value used).

Possible solutions
- Experiment with https://developer.apple.com/documentation/compositorservices/layerrenderer/drawable/4082130-depthrange more?
- Stream the depth buffers from SteamVR? Requires bandwidth, but lower resolution maps would be adequate probably.
- Roll our own timewarp/spacewarp implementation and always render the Drawable with the latest headpose anchor (Drawable is directly in front of the eyes)

**Comment by shadowfacts** [comment]
> Stream the depth buffers from SteamVR? Requires bandwidth, but lower resolution maps would be adequate probably.

This is the most promising, IMO. But it’s worth noting the that the OpenVR docs say depth buffers aren’t provided by all games, and it needs to be plumbed all the way through ALVR.
