### ISSUE TITLE
[BUG] repack_alvr_client fails on missing platfroms in vtool

### ISSUE THREAD

**Issue by onlymice** [alvr-org/alvr-visionos#32]
I'm building on m2 > Sonoma 14.3.1
Xcode at: Version 15.2 (15C500b)
Vision OS 1.0 and iOS 17.2 are installed in platforms section of Xcode, Vision pro is paired

I've tried going through the default process described on wiki, but it failed for me at 
`vtool -arch arm64 -set-build-version xros 1.0 1.0 -replace -output alvrrepack/xros/libalvr_client_core.dylib alvrrepack/ios/libalvr_client_core.dylib`

The logs from running repack_alvr_client.sh manually:
```zsh
./repack_alvr_client.sh
[cctools-port]: generating fake signature for 'alvrrepack/ios/libalvr_client_core.dylib'
vtool warning: code signature will be invalid for alvrrepack/maccatalyst/libalvr_client_core.dylib
[cctools-port]: generating fake signature for 'alvrrepack/maccatalyst/libalvr_client_core.dylib'
error: unknown platform: xros
usage: vtool [-arch <arch>] ... <show_command> <file>
       vtool [-arch <arch>] ... <set_command> ... [-replace] [-output <output>] <file>
       vtool [-arch <arch>] ... <remove_command> ... [-output <output>] <file>
       vtool -help
  show_command is exactly one of:
    -show
    -show-build
    -show-source
    -show-space
  set_command is one or more of:
    -set-build-version <platform> <minos> <sdk> [-tool <tool> <version>] ...
    -set-build-tool <platform> <tool> <version>
    -set-version-min <platform> <minos> <sdk>
    -set-source-version <version>
  remove_command is one or more of:
    -remove-build-version <platform>
    -remove-build-tool <platform> <tool>
    -remove-source-version
```

`vtool -help ` returns this list of available platforms
platform is one of:
    macos
    ios
    watchos
    tvos
    bridgeos
    maccatalyst
    uikitformac
    iossim
    watchossim
    driverkit

**Comment by jacobkring** [comment]
So, I ran into this issue and the problem was related to having multiple installations of vtool. In my case it was Conda, make sure you're using the xcode version of vtool

**Comment by onlymice** [comment]
thx @jacobkring, i've found out that my local anaconda setup messed with my terminal env

**Comment by inesdoreau** [comment]
I just had the same issue and was trying to found out why because Xcode was my only installation using tool. Turn out apple change the os name from "xros" and "xrossim" to "visionos" and "visionossim". 
So In the `repack_alvr_client.sh` I replaced this 

> xcrun vtool -arch arm64 -set-build-version xros 1.0 1.0 -replace -output alvrrepack/xros/$target_lib alvrrepack/ios/$target_lib
xcrun vtool -arch arm64 -set-build-version xrossim 1.0 1.0 -replace -output alvrrepack/xrsimulator/$target_lib alvrrepack/ios/$target_lib

with this : 

> xcrun vtool -arch arm64 -set-build-version visionos 1.0 1.0 -replace -output alvrrepack/xros/$target_lib alvrrepack/ios/$target_lib
xcrun vtool -arch arm64 -set-build-version visionossim 1.0 1.0 -replace -output alvrrepack/xrsimulator/$target_lib alvrrepack/ios/$target_lib
