### ISSUE TITLE
SwiftUI lobby

### ISSUE THREAD

**Issue by shinyquagsire23** [alvr-org/alvr-visionos#40]
The Android versions keep the lobby in VR-mode, IMO it'd be better to take inspiration from Steam Link and use a native UI for commecting, and only enter VR mode once a connection is established.

Probably even more true now that we know VR mode is limited to half res, so text won't be as clear as it could be.

**Comment by panthurrr** [comment]
https://github.com/panthurrr/VisionOSALVRClient/tree/SwiftUI-Entry

This replaces the entry point with a SwiftUI based lobby with a button to manually connect to ALVR.   Once the connection is separated from the immersive view we can enable/disable the button based on an active connection.

Having the manual button lets the user determine where they are in their environment before the 1.5m boundary is established which I've found useful in my testing.

I can make a PR for this in the current state if it's an improvement overall but it does not quite meet this feature request.  The code structure for the lobby is based on Apple's sample code if anyone wants to add more to it: https://developer.apple.com/documentation/visionos/world
