### ISSUE TITLE
I see only a cube RGB rotating

### ISSUE THREAD

**Issue by Clodo76** [alvr-org/alvr-visionos#42]
Newbie here, followed all steps, i see only a cube RGB rotating.

On PC, ALVR Dashboard show in Trusted clients the "Wired headset" green "Streaming". SteamVR: green "Connected".

I have this type of logs, i don't know if correlated, i can post a full log but it's big.

It's expected i see the SteamVR dashboard, right? Thx

`Pipeline (render) binary archive lookup failed for 'CC_ApplyStencilVertexFunction': Error Domain=AGXMetalG14G Code=3 "Failed to find binary in binary archives" UserInfo={NSLocalizedDescription=Failed to find binary in binary archives}
`

`Presenting a drawable without a device anchor. This drawable won't be presented.`

`The device_anchor can only be queried when the world tracking provider is running.`

**Comment by Fox-McCloud** [comment]
Try pressing and holding the dial and the left button for a bit, then force close ALVR. Re-launch and see if it connects.

Sometimes regularly closing it and re-opening it will also do the trick.

**Comment by Clodo76** [comment]
I force close (in AVP) and restart a lots of time, also restart anything, nothing change. I always see the RGB cube.
MacOS is the latest Sonoma, the latest xCode.
Windows11 ALVR nightly, SteamVR has only "alvr_server" add-on enabled.
The real issue maybe SteamVR is always "in searching" of headset:
https://www.clodo.it/host/images/e3220967c7fb2d3066d7fd0ff51c832b1afdfa73.png

I want to try ALVR on VisionPro without controller, for testing simracing, i never try to use Open Space Calibrator or anything else outside ALVR.

Any suggestion? Thx

**Comment by shinyquagsire23** [comment]
Make sure you have the headset resolution set to Medium or lower, it will fail to decode if it isn't

**Comment by Clodo76** [comment]
A quick question, can work (without controller of course) without OpenVR-SpaceCalibration?
Only to understand where i can focus the troubleshooting.


Thank you anyway for the feedback above, I really respect you and can't wait to try this project.
