### ISSUE TITLE
Maybe a dumb question, but is a developer strap needed?

### ISSUE THREAD

**Issue by Yzord** [alvr-org/alvr-visionos#44]
Title says it all. I followed the building instruction and got stuck where i had to select the current device, then click on Manage Run Destinations. It isn't available and then i thought, you have to connect the avp to it i guess.

So no luck when you have no developer strap? Because as a foreigner i can't get one also :(

**Comment by shinyquagsire23** [comment]
It's not, check the build guide on the wiki for pairing instructions
