### ISSUE TITLE
Why is TestFlight telling me "the SwiftSupport folder is missing"?

### ISSUE THREAD

**Issue by Wowfunhappy** [alvr-org/alvr-visionos#52]
I'm trying to get the visionOS client loaded onto my Vision Pro. I tried following the [build instructions](https://github.com/alvr-org/alvr-visionos/wiki/Building), but for some reason, I can't get my Vision Pro to appear in the list of run destinations. The Vision Pro _says_ that it's paired to my Mac, and the headset appears in XCode's "Manage Run Destinations" window. For some reason, however, the headset does not appear in the dropdown of the main XCode window.

The problem is likely that I'm using an Intel Mac (alongside some [secret Terminal commands](https://mastodon.social/@saagar@saagarjha.com/111788048762840638)). Regardless, since I _am_ able to build the app but can't seem to pair my headset, I figured I would try using TestFlight to get it into my device. I changed the name of the app and the bundle to be unique.

The app uploads to App Store Connect without issue, but a few minutes later, I consistently receive this email:

![Screen Shot 2024-02-17 at 8 49 40 PM](https://github.com/alvr-org/alvr-visionos/assets/4484096/fdf34c95-7651-4715-946d-3cd10f598acb)

I have _no_ idea what this means, and Google wasn't any help. I'm already using XCode 15.2, the current latest as far as I'm aware. Does anyone know if this error can be fixed?

If this is expected, or not actually related to alvr, I apologize! I was stuck and didn't know where else to ask!

**Comment by natefanaro** [comment]
https://github.com/alvr-org/alvr-visionos/blob/088ea714f74c3358cce2e700034b9677f01c5fec/ALVRClient.xcodeproj/project.pbxproj#L153

This line in the Xcode project mentions version 15.3. The project was probably saved with a newer version. I don’t think an older version of Xcode will try to fix it.

**Comment by Wowfunhappy** [comment]
Thank you. Unfortunately, I actually tried again yesterday with the Xcode 15.3 beta but kept getting the same problem.

**Comment by Wowfunhappy** [comment]
According to [Technical Note TN2435](https://developer.apple.com/library/archive/technotes/tn2435/_index.html#//apple_ref/doc/uid/DTS40017543-CH1-TROUBLESHOOTING-BUNDLE_ERRORS), Apple doesn't allow embedded dylib files in iOS/watchOS/tvOS, and breaking this rule causes ITMS-90426. VisionOS is not mentioned, but presumably has the same restriction.

You need to embed a .framework instead.

So somehow, ALVRClientCore needs to be compiled as a `.framework` instead of a `.dylib`. I messed around for a bit but couldn't figure out how to do this.

**Comment by zhuowei** [comment]
@Wowfunhappy I tried embedding the Rust library into a `.framework` in #67.

I don't have access to App Store Connect: does rebuilding with that pull request resolve the issue?

**Comment by dualist3** [comment]
This framework does not work properly on a VisionPro

**Comment by zhuowei** [comment]
@dualist3 What happens when you build it with the framework? Does it fail to build, or does it crash on launch; if it crashes, would you be able to share the crash message? Thank you so much.

(I don't have a Vision Pro, and it works on the Simulator)

**Comment by dualist3** [comment]
No crash, after connecting to SteamVR via ALVR and pressing the Enter button, the screen goes completely black

**Comment by zhuowei** [comment]
@dualist3 Thanks. I can't reproduce this on the visionOS Simulator, for what it's worth (connecting does work for me, and image does display); that's really weird.

**Comment by dualist3** [comment]
alvr connection is work But there is no image and no crash input
![Uploading 20240229105841.jpg…]()

**Comment by dualist3** [comment]
![20240229111026](https://github.com/alvr-org/alvr-visionos/assets/26101710/2bf57f52-c7f0-4c1d-98ee-5b89b4a877d5)
![20240229111030](https://github.com/alvr-org/alvr-visionos/assets/26101710/fd403362-a0d4-4092-afdf-346a23e2f53d)

**Comment by dualist3** [comment]
![Uploading 20240229105841.jpg…]()

**Comment by shadowfacts** [comment]
Do you have a recent version of the ALVR streamer? PR #67 is based off the main branch, which requires a newer streamer version than before—and the version mismatch can manifest as a completely black screen. I'm using this nightly build: https://github.com/alvr-org/ALVR-nightly/releases/tag/v21.0.0-dev00%2Bnightly.2024.02.23

**Comment by dualist3** [comment]
yes





------------------ Original ------------------
From: Shadowfacts ***@***.***&gt;
Date: Thu,Feb 29,2024 11:23 AM
To: alvr-org/alvr-visionos ***@***.***&gt;
Cc: dualist ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [alvr-org/alvr-visionos] Why is TestFlight telling me "theSwiftSupport folder is missing"? (Issue #52)

**Comment by dualist3** [comment]
The version being used is the ALVR-nightly

**Comment by Wowfunhappy** [comment]
I am sorry, I had to return my Vision Pro to Apple yesterday, so I am no longer able to test this. Thank you!

**Comment by shadowfacts** [comment]
@dualist3 Can you confirm which nightly version you're using? Zhuowei's branch works perfectly fine for me with the build from 2024.02.23.

**Comment by dualist3** [comment]
2024.02.27，I encountered this issue when using Zhuowei's branch to package it into an app and accessing it through tf. The tf link is located here https://testflight.apple.com/join/BXOkz2Cy

**Comment by ovo6477** [comment]
> 2024.02.27，I encountered this issue when using Zhuowei's branch to package it into an app and accessing it through tf. The tf link is located here https://testflight.apple.com/join/BXOkz2Cy

that testflight works but its a very old build it doesn't have the hand tracking controller support or any of the major bug fixes can anyone update that testflight with a newer build?
