### ISSUE TITLE
Failed Registering Bundle Identifier

### ISSUE THREAD

**Issue by Yzord** [alvr-org/alvr-visionos#54]
After following the wiki step by step i encounter an error when i try to build the visionOS client.

> Failed Registering Bundle Identifier: The app identifier "com.worthdoingbadly.ALVRClient" cannot be registered to your development team because it is not available. Change your bundle identifier to a unique string to try again.

It also spits the following error

> No profiles for 'com.worthdoingbadly.ALVRClient' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.worthdoingbadly.ALVRClient'.

I don't know what to do to be honest. Did i lost a step?

**Comment by Yzord** [comment]
Ok, let me start over again. Must have missed something

**Comment by Yzord** [comment]
Ok, i changed it, but i couldn't find the instructions on the building wiki page. Do i have a old version of it?

**Comment by ant2002k** [comment]
"Use a device-specific Development provisioning profile instead of a Distribution provisioning profile, or change the **com.worthdoingbadly.** prefix to your own registered bundle identifier prefix." I just used "com.example.xxx"

**Comment by Yzord** [comment]
Ah yes, it's under common issues. Not ment up in the building progress. Thanks for the clarification.
