### ISSUE TITLE
ALVR Won't Open on Mac

### ISSUE THREAD

**Issue by danielberman1** [alvr-org/alvr-visionos#73]
Hi I'm trying to get ALVR to run on my Vision Pro, all goes well until I try to input the hostname and IP into ALVR on my Mac and all I get is a generic "ALVR Client" Cannot be Opened.

Any thoughts? Stumped with this one

**Comment by zhuowei** [comment]
You'll need to install the [ALVR server](https://github.com/alvr-org/ALVR-nightly/releases) on a Windows or Linux PC with Steam and SteamVR installed. As far as I know, ALVR's server does not support macOS.

You can follow the [ALVR installation guide](https://github.com/alvr-org/ALVR/wiki/Installation-guide) here for setting up the server on Windows or Linux.

**Comment by danielberman1** [comment]
Thanks a bunch!
