### ISSUE TITLE
Jitter and video lag - large framerate variance

### ISSUE THREAD

**Issue by pwhizzard** [alvr-org/alvr-visionos#75]
I get a lot of jitter and it is interesting that the streamer FPS is so high above 90 (goes over 300). Here are a couple screenshots for framerate on extreme and then a couple on medium. I’ll include some iCloud video links for the screen recordings in case that’s helpful. It is choppy even at medium with the 200mbps. Tried multiple dedicated routers too. I’m happy to try and/ or test things. 

4090 with a dedicated router wired to pc running windows 11. Drivers all up to date. 
https://share.icloud.com/photos/0fau7WID0-MExa7k0XdhNuMEA

https://share.icloud.com/photos/0d9iHJeyfwWEH9K2FSk4xsALA

![IMG_0137](https://github.com/alvr-org/alvr-visionos/assets/6181652/0509bae0-b101-4151-be26-d93be6da35d4)
![IMG_0138](https://github.com/alvr-org/alvr-visionos/assets/6181652/9182f248-042e-4843-83ce-d42829d7833a)
![IMG_0139](https://github.com/alvr-org/alvr-visionos/assets/6181652/0b1c5d21-0e63-45a8-a0c8-91c86dfae831)
![IMG_0140](https://github.com/alvr-org/alvr-visionos/assets/6181652/be5223a6-e0c3-4c90-8130-46f5346c1570)

**Comment by shinyquagsire23** [comment]
If it's only jittering in the SteamVR overlay/boundaries, that's an ALVR runtime bug, is the game itself also jittering?

The FPS is somewhat expected, there's an option to clamp that iirc but it can cause some stuttering

**Comment by pwhizzard** [comment]
Most of the time SteamVR overlay is fine. In-game is when the video lag is most predominant. Especially if I get to 200+mbps.

**Comment by pwhizzard** [comment]
Not sure what it was but I uninstalled, reinstalled, and reset all of my settings in ALVR and it seems to be fine now on medium. Bumping up to Extreme still makes everything really laggy, but I would guess that is expected. I'll close this out. SFTN

Oh and for what is worth, 'Optimize game render latency' does clamp down the FPS.
