### ISSUE TITLE
Foveated encoding/decoding

### ISSUE THREAD

**Issue by shinyquagsire23** [alvr-org/alvr-visionos#8]
Maybe look at https://github.com/shinyquagsire23/monado/blob/macos_ql_merge/src/xrt/drivers/quest_link/ql_hmd.cpp#L140 and verify it's the same as ALVR's foveation?

**Comment by zhuowei** [comment]
Supposedly they're [using the Oculus foveation](https://github.com/alvr-org/ALVR/wiki/How-ALVR-works#foveated-encoding), so it should be the same.

I had a go at converting [their shader](https://github.com/alvr-org/ALVR/blob/c4095ac7c48046615d2b7757a7d9dadc6b54de4b/alvr/client_core/cpp/ffr.cpp#L35) to [Metal](https://github.com/VisionOSALVR/VisionOSALVRClient/blob/d50b9aecdd859bd795ff7c7b19f2d131ad402e51/ALVRClient/Shaders.metal#L56), but haven't tried using it.

**Comment by zarik5** [comment]
I would like to chime in, I'm in the process of rewriting the current opengl client renderer using wgpu. wgpu is an abstraction layer that supports multiple graphics apis, including Metal. but also I don't want to break your momentum so you can go ahead and implement this in parallel. I will notify you when I'm done with the wgpu rewrite.
