### ISSUE TITLE
Non Issue-testflight 

### ISSUE THREAD

**Issue by ovo6477** [alvr-org/alvr-visionos#87]
will there be a new testflight bulid soon?
there was an old testflight build posted but it hasn't been updated in a long time it doesn't support the new features like emulated valve controllers and has the major bugs and crashes still please let me know thank you

**Comment by shinyquagsire23** [comment]
testflight is out 🎉

**Comment by ovo6477** [comment]
NIce! Thank you I appreciate all the hard work!
