### ISSUE TITLE
Is it inoperable without a controller?

### ISSUE THREAD

**Issue by dualist3** [alvr-org/alvr-visionos#98]
Is the hand tracking currently inoperable like quest2?Is it inoperable without a controller?

**Comment by ovo6477** [comment]
u can use the hand tracking as emulated controllers its in the ALVR setting

**Comment by dualist3** [comment]
> u can use the hand tracking as emulated controllers its in the ALVR setting

Can you tell me how to set it up? The setting method I found in the ALVR's Wiki doesn't work.
