### ISSUE TITLE
Build Issues

### ISSUE THREAD

**Issue by dsshean** [alvr-org/alvr-visionos#99]
Hi I tried to troubleshoot this issue for a couple of days and chalked it up to my lack of inexperience with ios development, but im getting this issue:  

Code signing identifier (ALVRClientCore) does not match bundle identifier (alvr.ALVRClientCore) for /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.6vLjXQ/extracted/ALVRClient.app/Frameworks/ALVRClientCore.framework

Old build installed correctly and worked fine.  

Deleted the local repo/ redownload /rebuild / deleted installed app on visionpro.  etc... nothing has worked.

Building works fine, but fails at install stage on the vision pro. Any help would be greatly appreciated.

Thanks,
Doug

**Comment by danielteeny** [comment]
exact same issue. 

installed it once before without issue, tried installing it after purchasing apple developer account and can't get the app which says it builds correctly on the device.

**Comment by niv-d** [comment]
Change your identifier, run the build in xcode, and then rerun ./build_and_repack
Build again in xcode.


Seems to fix

**Comment by balarayen** [comment]
For those who are still facing this issue, run `conda deactivate` and the run `./build_and_repack.sh` to overcome this error.
